
export interface EhrModelEvent {
  name:EhrModelEventType;
  data:any;
}

export enum EhrModelEventType {
  EVENT_CHILDREN_UPDATED,
  EVENT_MIN_UPDATED,
  EVENT_MAX_UPDATED,
  EVENT_IS_READ_ONLY,
  EVENT_TOOLTIP_VALUE,
  EVENT_ANNOTATION_VALUE,
  EVENT_IS_HIDDEN,
  EVENT_STRUCTURED_VALIDATION_CHANGE,
  CLEAR_VALUE_EVENT,
  EVENT_MODEL_VALIDATION_CHANGE
}
